sudo: required
language: elixir

elixir:
  - 1.8
  - 1.9

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - mkdir ${PWD}/mongodb
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz --strip-components=1 -C ${PWD}/mongodb

before_script:
  - export PATH=${PWD}/mongodb/bin/:$PATH
  - bash ./start_mongo.bash
  - mkdir ${PWD}/mongodb/data
  - ${PWD}/mongodb/bin/mongod --dbpath ${PWD}/mongodb/data --logpath ${PWD}/mongodb/mongodb.log --fork

script:
  - mix local.hex --force
  - mix deps.get
  - mix test

env:
  matrix:
    - MONGODB=3.2.20
    - MONGODB=3.4.16
    - MONGODB=3.6.6
    - MONGODB=ubuntu1604-v4.2-latest
