sudo: required
language: elixir

elixir:
#  - 1.4
#  - 1.5
#  - 1.6
#  - 1.7
  - 1.8

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version

cache:
  - apt
  - directories:
    - ~/.mongodb
    - ./plt_core_path

before_script:
  - export PATH=${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/:$PATH
  - bash ./start_mongo.bash
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

script:
  - mix local.hex --force
  - mix deps.get
  - mix test

env:
  matrix:
    - MONGODB=3.2.20
    - MONGODB=3.4.16
    - MONGODB=3.6.6
    - MONGODB=4.0.9
